{{- if .Values.adminIngress.enabled -}}
{{- $svcName := printf "%s-admin" (include "featherbit-gateway.fullname" .) -}}
{{- $svcPort := .Values.adminService.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "featherbit-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  {{- with .Values.adminIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.adminIngress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.adminIngress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.adminIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
