entryPoints:
  web:
    address: ":8000"
  websecure:
    address: ":8443"
providers:
  file:
    filename: /etc/traefik/bench/dynamic.yml
log:
  level: WARN
serversTransport:
  maxIdleConnsPerHost: 512
global:
  checkNewVersion: false
  sendAnonymousUsage: false
